[vm]
ProjetFilRouge ansible_host=192.168.1.37 ansible_user=freebox ansible_connection=local

# ansible_connection=local = Ansible s'exécute directement sur la VM
# (pas besoin de SSH puisqu'on est déjà dessus)

[vm:vars]
ansible_python_interpreter=/usr/bin/python3
k3s_version=v1.30.4+k3s1
helm_version=v3.15.4
domain_dev=fastapi_dev.laurenthoarau.cloud-ip.cc
domain_staging=fastapi_staging.laurenthoarau.cloud-ip.cc
domain_prod=fastapi_prod.laurenthoarau.cloud-ip.cc
public_ip=88.120.42.53
vm_ip=192.168.1.37
acme_email=votre@email.com          # ← Votre email
kubeconfig=/home/freebox/.kube/config
